[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library @ ^3.0.1
    bblanchon/ArduinoJson @ ^7.0.0
    earlephilhower/ESP8266Audio @ ^1.9.7
    tzapu/WiFiManager @ ^2.0.17